### ISSUE TITLE
non-ascii characters in file name cause UnicodeEncodeError

### ISSUE THREAD

**Issue by Rizziepit** [Starou/django-thumborstorage#11]
I'm running into a `UnicodeEncodeError` when I try to save a file with non-ascii characters in the file name. A solution would be to utf-8 encode the name [here](https://github.com/Starou/django-thumborstorage/blob/master/django_thumborstorage/storages.py#L88). I'm using Django 1.6.10, Python 2.7 and django-thumborstorage 0.91.7. To reproduce:
```python
from django.core.files.base import ContentFile
from django_thumborstorage.storages import ThumborStorage

storage = ThumborStorage()
storage.save(u'‘Ø', ContentFile(''))
```

I'm happy to implement a fix and open a PR.

**Comment by Starou** [comment]
Hi @Rizziepit,

Unfortunately, I think we cannot just encode as utf-8 since the *name* is a [header parameter](https://github.com/Starou/django-thumborstorage/blob/master/django_thumborstorage/storages.py#L30) which must be ascii encoded. I am not an http protocol specialist but this is what I understand from these discussions:

1. https://bugs.python.org/issue22231
2. http://stackoverflow.com/questions/5423223/how-to-send-non-english-unicode-string-using-http-header

As suggested in 1), we could quote the name and then unquote it (to store it with the unicode chars in your database):

```python
        headers = {
            "Content-Type": mimetypes.guess_type(self.name)[0] or "image/jpeg",
            "Slug": urllib.quote(self.name.encode('utf-8'), ':/?#[]@!$&\'()*+,;='),
        }
        response = requests.post(url, data=image_content, headers=headers)
        self._location = urllib.unquote(response.headers["location"])
        return super(ThumborStorageFile, self).write(image_content)
```

But this need to be carefully tested.

I don't have this pb because I apply the following on the filename in the *upload_to* function:

```python
def strip_accents(str):
    return unicodedata.normalize('NFD', unicode(str)).encode('ascii', 'ignore')
```

**Comment by Rizziepit** [comment]
Hi @Starou. The `urllib.quote` solution looks good. I can try my hand at implementing it with tests. If you'd rather not go that route, adding a note about the `upload_to` workaround in the readme might be good enough. The `upload_to` workaround is fine for my application, but it does shortchange non-Latin alphabet languages.

**Comment by Starou** [comment]
I'd say go ahead with `quote()`!
I made a quick test on a project of mine without problem except that having a MySQL instance with latin-9 encoding, I get some `?` instead of unicode characters and some warning in the runserver console, but that's all.
