### ISSUE TITLE
django.security.SuspiciousFileOperation Detected path traversal attempt

### ISSUE THREAD

**Issue by pmg103** [Starou/django-thumborstorage#29]
This change in Django 3.2.11 https://github.com/django/django/commit/6d343d01c57eb03ca1c6826318b652709e58a76e appears to break ThumborStorage. When uploading files I get a failure and the following exception:

    django.security.SuspiciousFileOperation Detected path traversal attempt in '/image/8d7e08134015fc0430fbc3b484d424cd/test.png'

**Comment by pmg103** [comment]
A quick solution could be to override `django.core.files.storage.Storage.save()` in `ThumborStorage` with the old implementation (ie not calling validate_file_name()), but I don't know if the implications may run deeper than this.

**Comment by Starou** [comment]
Thanks for the report, I'll look into it when upgrading a project in Django 3.2 next month.

**Comment by Starou** [comment]
@pmg103 : a PR #30  is on its way. Everything looks OK but I'll make a release after a couple of weeks in production to be sure that I haven't missed something in the backward compatibility with the previous release, since in that PR path are now stored in the database without a leading `/` and I have to handle both "legacy" (with the leading `/`) and new-style paths.

**Comment by AdrianRibao** [comment]
Thanks @Starou ! do you have a date in mind to merge and release a new version?

**Comment by Starou** [comment]
Done (2.0.0).
